stages:
  # - ansible-lint
  - install_ynh
  - ansible_tests

# ansible-lint:
#   only:
#       - master
#   stage: ansible-lint
#   image: yokogawa/ansible-lint
#   allow_failure: true
#   script:

  # - 'ansible-lint setup.yml'

install_ynh:
  tags:
    - ynh
  only:
    - master
  stage: install_ynh
  # Requires privileged container
  
  script:
    # - /bin/echo
    # - echo "Test succeeded w/ custom executor!"
    # Deploy git repos
    - 'cd $CI_PROJECT_DIR; echo "Cloning YunoHost projects..."; ./deploy.sh'
    # install yunohost
    - apt install --yes sudo wget
    - 'cd $CI_PROJECT_DIR; echo "Installing YunoHost..."; ./prebuild.sh'
    # - /etc/yunohost/installed
    - /usr/bin/yunohost tools postinstall -d ynh.local -p ynhynhynh
    - /usr/bin/yunohost user create johndoe -f John -l Doe -m john.doe@ynh.local -q 0 -p ynhynhynh --admin-password ynhynhynh
    - /usr/bin/yunohost tools diagnosis
    
ansible_tests:
  tags:
    - ynh
  only:
    - master
  stage: ansible_tests
  script:
    - "apt install --yes gnupg2"
    - 'echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" > /etc/apt/sources.list.d/ansible.list'
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
    - apt update
    - apt install --yes ansible software-properties-common
    - 'cd $CI_PROJECT_DIR; ansible-playbook --connection=local test.yml -vv'