stages:
  # - ansible-lint
  - deploy_app
  - ansible_tests

# ansible-lint:
#   only:
#       - master
#   stage: ansible-lint
#   image: yokogawa/ansible-lint
#   allow_failure: true
#   script:

  # - 'ansible-lint setup.yml'

deploy_app:
  tags:
    - ynh
  only:
    - master
  stage: deploy_app
  # Requires privileged container
  
  script:
    # - /bin/echo
    # - echo "Test succeeded w/ custom executor!"
    # Deploy git repos
    - 'cd $CI_PROJECT_DIR; echo "Cloning YunoHost projects..."; ./deploy.sh'
    # install yunohost
    - apt install --yes sudo wget
    - 'cd $CI_PROJECT_DIR; echo "Installing YunoHost..."; ./prebuild.sh'
    - /etc/yunohost/installed
    - /usr/bin/yunohost tools diagnosis
    
ansible_tests:
  tags:
    - ynh
  only:
    - master
  stage: ansible_tests
  script:
    - 'apt-add-repository --yes "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main"'
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
    - apt update
    - apt install --yes ansible software-properties-common
    - 'cd $CI_PROJECT_DIR; ansible-playbook --connection=local test.yml -vv'