stages:
  # - ansible-lint
  - deploy_app

# ansible-lint:
#   only:
#       - master
#   stage: ansible-lint
#   image: yokogawa/ansible-lint
#   allow_failure: true
#   script:

  # - 'ansible-lint setup.yml'

deploy_app:
  tags:
    - ynh
  only:
    - master
  stage: deploy_app
  # Requires privileged container
  
  script:
    # - /bin/echo
    # - echo "Test succeeded w/ custom executor!"
    # Deploy git repos
    - 'cd $CI_PROJECT_DIR; echo "Cloning YunoHost projects..."; ./deploy.sh'
    # install yunohost
    - 'cd $CI_PROJECT_DIR; echo "Installing YunoHost..."; ./prebuild.sh'
    - apt install --yes sudo software-properties-common
    - 'apt-add-repository --yes --update ppa:ansible/ansible'
    - apt install --yes ansible
    - 'cd $CI_PROJECT_DIR; ansible-playbook --connection=local test.yml -vv'