concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Scaleway"
  url = "https://gitlab.com/"
  token = "eRaxMNUjk8Whyn-GPxgM"
  executor = "custom"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.custom]
    prepare_exec = "/opt/lxd-executor/prepare.sh"
    run_exec = "/opt/lxd-executor/run.sh"
    cleanup_exec = "/opt/lxd-executor/cleanup.sh"
        # prepare_args = "CUSTOM_ENV_CI_IMAGE_ID" # Image arg