[[runners]]
  name = "lxd-executor"
  url = "https://gitlab.com/"
  token = "3U7VpLNzZe99vwZcRt49"
  executor = "custom
  builds_dir = "/builds"
  cache_dir = "/cache"
  [runners.custom]
    prepare_exec = "lxd-executor/prepare.sh" # Path to a bash script to create lxd container and download dependencies.
    run_exec = "lxd-executor/run.sh" # Path to a bash script to run script inside the container.
    cleanup_exec = "lxd-executor/cleanup.sh" # Path to bash script to delete container.
