galaxy_info:
  author: e_lie
  description: Deploy Yunohost with Ansible
  license: GPL-v3
  min_ansible_version: 1.2
  galaxy_tags: [yunohost]
  platforms:
  - name: Debian
    versions:
      - jessie
      - stretch
  categories:
    - cloud
    - web

dependencies: []
